modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "examplemod"
version = "${version}"
displayName = "ExampleMod"
authors = "Example Author"
description = '''
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21]"
ordering = "NONE"
side = "BOTH"
